# Generated by Django 4.1.3 on 2023-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('publication_date', models.DateTimeField()),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
    ]
